backend:
  name: github
  repo: thecotilking/dominion-group-of-schools
  branch: main
  base_url: https://dominiongroupofschools.com
  auth_endpoint: api/auth

media_folder: "assets/photos/news-uploads"
public_folder: "assets/photos/news-uploads"

collections:
  - name: "news"
    label: "News & Events"
    label_singular: "News Post"
    folder: "content/news"
    create: true
    delete: true
    slug: "{{slug}}"
    identifier_field: title
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD" }
      - label: "Photos"
        name: "images"
        widget: "list"
        required: false
        field: { label: "Photo", name: "image", widget: "image" }
      - { label: "Summary", name: "body", widget: "text" }
